#define LOCALDNS 8089
#define ROOTPORT 4541      
#define TLDPORT 4542       //THE TLD AND AUTH ARE TO BE RECEIVED FROM ROOT AND TLD SERVERS RESPECTIVELY
#define AUTHPORT 4545     //BUT WE HARD CODE AS THIS IS A SIMULATION ONLY FOR UNDERSTANDING PURPOSES.
#define LOCALPORT 8089