main:
	gcc -o ./authDNS/authDNS ./authDNS/server.c
	gcc -o ./localDNS/localDNS ./localDNS/server.c
	gcc -o ./rootDNS/rootDNS ./rootDNS/server.c
	gcc -o ./TLD/TLD ./TLD/server.c
	gcc -o ./client/client ./client/client.c
